package semanticrfpresponse;

/**
 *
 * @author kharper
 */
public class RegexHelper {
    private static final String REGEX_PATTERN_ALPHA_NUMERIC = "[^a-zA-Z ]";
    private static final String REGEX_COMMON_WORDS = "(?:^|(?<= ))("
            + "a|"
            + "all|"
            + "an|"
            + "and|"
            + "andor|"
            + "any|"
            + "as|"
            + "at|"
            + "are|"
            + "be|"
            + "been|"
            + "being|"
            + "but|"
            + "by|"
            + "can|"
            + "contains|"
            + "each|"
            + "etc|"
            + "for|"
            + "from|"
            + "has|"
            + "have|"
            + "how|"
            + "if|"
            + "in|"
            + "into|"
            + "is|"
            + "it|"
            + "must|"
            + "no|"
            + "not|"
            + "nor|"
            + "of|"
            + "on|"
            + "one|"
            + "or|"
            + "our|"
            + "please|"
            + "was|"
            + "were|"
            + "what|"
            + "when|"
            + "where|"
            + "which|"
            + "who|"
            + "whom|"
            + "will|"
            + "with|"
            + "within|"
            + "shall|"
            + "so|"
            + "such|"
            + "than|"
            + "that|"
            + "the|"
            + "these|"
            + "they|"
            + "this|"
            + "to|"
            + "yet"
            + ")(?:(?= ))";
    
    public static String applyRegexToSentence(String sentence) {
        return sentence.replaceAll(REGEX_PATTERN_ALPHA_NUMERIC, "").replaceAll(REGEX_COMMON_WORDS, "");
    }
}
